name: 'Build, lint and test'

on:
    push:
        paths-ignore:
            - '**.md'
    pull_request:
        paths-ignore:
            - '**.md'
    schedule:
        - cron: '0 0 1 * *'

jobs:
    lint-and-tsc:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install
              run: npm ci

            - name: Format
              run: npx prettier --check src/

            - name: Lint
              run: npm run lint

            - name: TypeScript
              run: npm run compile

            - name: Unit tests
              run: npm test

            - name: Check if package was just generated
              run: npm run generate-package && git diff --exit-code
